// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdnuswekfcjgvqyiotoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkbnVzd2VrZmNqZ3ZxeWlvdG9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNzg4ODIsImV4cCI6MjA1Mzg1NDg4Mn0.JSfw_eiWrKaiPhxIaqSX_G1BTuFrpMn25IFpROASEZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);